# Model arguments
# model_name_or_path: deepseek-ai/deepseek-coder-7b-base-v1.5
model_name_or_path: /cm/shared/anhdtv7/mainframe_gpt/data/deepseek-7b-ft-full
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: false
trust_remote_code: true

# Data training arguments
dataset_mixer:
  # HuggingFaceH4/ultrachat_200k: 1.0
  /cm/archive/hieudt47/workspace/data/mainframe_df_v1.1_chunks_8096.feather: 0.1
  /cm/archive/hieudt47/workspace/data/textbook_quality_programming.feather: 0.1
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: steps
gradient_accumulation_steps: 2
gradient_checkpointing: true
hub_model_id: deepseek-7b-ft-full_longcontext
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 16000
max_steps: -1
num_train_epochs: 1
output_dir: data/deepseek-7b-ft-full_longcontext
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
# save_strategy: "epoch"
save_strategy: "steps"
save_steps: 100
save_total_limit: null
seed: 42
tf32: true
