# Model arguments
model_name_or_path: /cm/shared/anhdtv7/mainframe_gpt/data/deepseek_16b_lora
model_revision: main
torch_dtype: float16
use_flash_attention_2: true
trust_remote_code: true



# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- lm_head
- up_proj
- down_proj

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['from'] == 'human' %}\n{{ '<|user|>\n' + message['value'] + eos_token }}\n{% elif message['from'] == 'system' %}\n{{ '<|system|>\n' + message['value'] + eos_token }}\n{% elif message['from'] == 'gpt' %}\n{{ '<|assistant|>\n'  + message['value'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  # HuggingFaceH4/ultrachat_200k: 1.0
  /cm/archive/hieudt47/workspace/data/mainframe_df_v1.1.feather: 1
  /cm/archive/hieudt47/workspace/data/textbook_quality_programming.feather: 1
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: deepseek_instruct_lora_16b_multigpu
hub_strategy: every_save
learning_rate: 2.0e-04
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 3
output_dir: data/deepseek_instruct_lora_16b_multigpu
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 3
push_to_hub: false
# dataset_num_proc: 4
report_to:
- tensorboard
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1